# Generated by Django 5.1.6 on 2025-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('counted_view', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('published_date', models.DateField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
