# Generated by Django 5.1.6 on 2025-03-05 16:03

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Hashem/Documents/GitHub/MySite/MySite/media')),
        ),
    ]
